### ISSUE TITLE
Samplot is changing chromosome name

### ISSUE THREAD

**Issue by Rohit-Satyam** [ryanlayer/samplot#165]
Hi 
I am getting the following error when trying to run `samplot` for a sample aligned to P vivax Sal1.
```
amplot plot -n pvall -b pvall.sorted.bam -o pvall.chr1.png -c Pv_Sal1_chr01 -s 1 -e 830022 --coverage_only -H 2
[W::hts_idx_load3] The index file is older than the data file: pvall.sorted.bam.bai
Traceback (most recent call last):
  File "/home/subudhak/miniconda3/lib/python3.8/site-packages/samplot/samplot.py", line 2705, in get_read_data
    bam_iter = bam_file.fetch(r.chrm, max(0, r.start - 1000), r.end + 1000)
  File "pysam/libcalignmentfile.pyx", line 1091, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 685, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `Pv_Sal1_01`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/subudhak/miniconda3/bin/samplot", line 10, in <module>
    sys.exit(main())
  File "/home/subudhak/miniconda3/lib/python3.8/site-packages/samplot/__main__.py", line 31, in main
    args.func(parser, args, extra_args)
  File "/home/subudhak/miniconda3/lib/python3.8/site-packages/samplot/samplot.py", line 3576, in plot
    read_data, max_coverage = get_read_data(
  File "/home/subudhak/miniconda3/lib/python3.8/site-packages/samplot/samplot.py", line 2712, in get_read_data
    bam_iter = bam_file.fetch(chrm, max(0, r.start - 1000), r.end + 1000)
  File "pysam/libcalignmentfile.pyx", line 1091, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 685, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `chrPv_Sal1_01`
```
Command used is `samplot plot -n pvall -b pvall.sorted.bam -o pvall.chr1.png -c Pv_Sal1_chr01 -s 1 -e 830022 --coverage_only -H 2` and the region to be plotted is first chromosome.
```
Pv_Sal1_chr01	1	830022
```
I checked the BAM file and the chromosome names in it are correct. What could be wrong?

![Screenshot from 2022-09-25 17-08-06](https://user-images.githubusercontent.com/55479480/192161841-2308e173-6cd7-49aa-acf4-88d833d86728.png)

## Update 1

I tried removing `chr` from the chromosome names and it works. However, the mitochondrial coverage plotis wrong. Below are attached IGV sanpshot and the Samplot output

![image](https://user-images.githubusercontent.com/55479480/192161908-f13d9e8b-61b5-4e74-a730-20c8499cfa9b.png)

![pvall_PVAD80_MIT](https://user-images.githubusercontent.com/55479480/192161966-04ce3dbd-fba5-46c0-9f87-6eb654865032.png)

**Comment by bmansfeld** [comment]
Hi, 
I second this. 
It seems that samplot expects only chromosomes named "chr##".
It would be great if you could set the chr prefix if needed.
Thanks,
Ben

**Comment by wangjie07070910** [comment]
Hi,
Thanks for this useful tool. I installed it by conda and still got the chromosome name issue, what should I do? 
(samplot) jj@build-stretch:/netscratch/dep_mercier/grp_novikova/Neobatrachus/Jie/software$ time samplot plot -n 102233 -b /netscratch/dep_mercier/grp_novikova/Neobatrachus/Jie/stlfr2supernova_pipeline/work/102233_out/deepvariant_dir/ema_final.bam -o 102233.png -c Sc_35827 -s 156435596 -e 156435993 -t DEL
Window size is under 1.5x the estimated fragment length and will be resized to 394. Rerun with -w 198 to override
Traceback (most recent call last):
  File "/netscratch/dep_mercier/grp_novikova/Neobatrachus/Jie/conda/anaconda3/envs/samplot/lib/python3.7/site-packages/samplot/samplot.py", line 2705, in get_read_data
    bam_iter = bam_file.fetch(r.chrm, max(0, r.start - 1000), r.end + 1000)
  File "pysam/libcalignmentfile.pyx", line 1081, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 686, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `Sc_35827`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/netscratch/dep_mercier/grp_novikova/Neobatrachus/Jie/conda/anaconda3/envs/samplot/bin/samplot", line 10, in <module>
    sys.exit(main())
  File "/netscratch/dep_mercier/grp_novikova/Neobatrachus/Jie/conda/anaconda3/envs/samplot/lib/python3.7/site-packages/samplot/__main__.py", line 31, in main
    args.func(parser, args, extra_args)
  File "/netscratch/dep_mercier/grp_novikova/Neobatrachus/Jie/conda/anaconda3/envs/samplot/lib/python3.7/site-packages/samplot/samplot.py", line 3588, in plot
    options.ignore_hp,
  File "/netscratch/dep_mercier/grp_novikova/Neobatrachus/Jie/conda/anaconda3/envs/samplot/lib/python3.7/site-packages/samplot/samplot.py", line 2712, in get_read_data
    bam_iter = bam_file.fetch(chrm, max(0, r.start - 1000), r.end + 1000)
  File "pysam/libcalignmentfile.pyx", line 1081, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 686, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `chrSc_35827`

real	0m1.028s
user	0m0.672s
sys	0m0.132s


Thanks,
Jie
