### ISSUE TITLE
plot with transcripts error

### ISSUE THREAD

**Issue by abrusell** [ryanlayer/samplot#190]
I've downloaded, sorted and indexed the gff3 file from ensembl, but when I use it with samplot plot -T I get the following error:
```
$ samplot plot -c chr14 -s 103334932 -e 103491427 -t DEL -T $db/hg38/Samplot/Homo_sapiens.GRCh38.110.sort.gff3 -r $db/hg38/reference/Homo_sapiens_assembly38.fasta -o DEL00117515 -b prob_markdup.bam father_markdup.bam mother_markdup.bam  -n PROB FATHER MOTHER 
Traceback (most recent call last):
  File "/g100/home/userexternal/abrusell/miniconda3/envs/samplot/bin/samplot", line 10, in <module>
    sys.exit(main())
  File "/g100/home/userexternal/abrusell/miniconda3/envs/samplot/lib/python3.9/site-packages/samplot/__main__.py", line 31, in main
    args.func(parser, args, extra_args)
  File "/g100/home/userexternal/abrusell/miniconda3/envs/samplot/lib/python3.9/site-packages/samplot/samplot.py", line 3655, in plot
    plot_transcript(
  File "/g100/home/userexternal/abrusell/miniconda3/envs/samplot/lib/python3.9/site-packages/samplot/samplot.py", line 3419, in plot_transcript
    transcript_plan = get_transcript_plan(ranges, transcript_file)
  File "/g100/home/userexternal/abrusell/miniconda3/envs/samplot/lib/python3.9/site-packages/samplot/samplot.py", line 3331, in get_transcript_plan
    genes[info["Name"]] = [
KeyError: 'Name'
```

**Comment by pontushojer** [comment]
This was fixed in https://github.com/ryanlayer/samplot/pull/157. I guess you are using samplot through conda? The change is not implemented in that version. Try installing the development version e.g. 

```
pip install git+https://github.com/ryanlayer/samplot.git
```

**Comment by abrusell** [comment]
Thank you,
fixed!
