### ISSUE TITLE
 Population must be a sequence.

### ISSUE THREAD

**Issue by animesh** [ryanlayer/samplot#202]
Trying to test the program but getting this error

```
samplot plot -n N1 N2 N3 -b TK91L003.markdup.sorted.bam TK93L003.markdup.sorted.bam TK91L002.markdup.sorted.bam -o TK9N123 -c chr4 -s 115928726  -e 125931880
Traceback (most recent call last):
  File "/cluster/home/ash022/.conda/envs/samplot/bin/samplot", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/cluster/home/ash022/.conda/envs/samplot/lib/python3.12/site-packages/samplot/__main__.py", line 31, in main
    args.func(parser, args, extra_args)
  File "/cluster/home/ash022/.conda/envs/samplot/lib/python3.12/site-packages/samplot/samplot.py", line 3576, in plot
    read_data, max_coverage = get_read_data(
                              ^^^^^^^^^^^^^^
  File "/cluster/home/ash022/.conda/envs/samplot/lib/python3.12/site-packages/samplot/samplot.py", line 2773, in get_read_data
    read_data["all_pairs"] = downsample_pairs(
                             ^^^^^^^^^^^^^^^^^
  File "/cluster/home/ash022/.conda/envs/samplot/lib/python3.12/site-packages/samplot/samplot.py", line 2790, in downsample_pairs
    all_pairs[bam_i][hp_i] = sample_normal(
                             ^^^^^^^^^^^^^^
  File "/cluster/home/ash022/.conda/envs/samplot/lib/python3.12/site-packages/samplot/samplot.py", line 539, in sample_normal
    for read_name in random.sample(inside_norm.keys(), max_depth):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/ash022/.conda/envs/samplot/lib/python3.12/random.py", line 413, in sample
    raise TypeError("Population must be a sequence.  "
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
```

Any ideas how to get past this will be appreciated 💯

**Comment by jbelyeu** [comment]
I tried replicating the issue and did not succeed, but I'd suggest trying in a slightly back-dated conda environment with python v3.10.x instead of python 3.12.x. This issue looks like a dependency version problem.

**Comment by asan-emirsaleh** [comment]
The same problem while using python 3.12
```
Traceback (most recent call last):
  File "/home/asan/miniconda3/envs/samplot-env/bin/samplot", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/asan/miniconda3/envs/samplot-env/lib/python3.12/site-packages/samplot/__main__.py", line 31, in main
    args.func(parser, args, extra_args)
  File "/home/asan/miniconda3/envs/samplot-env/lib/python3.12/site-packages/samplot/samplot.py", line 3576, in plot
    read_data, max_coverage = get_read_data(
                              ^^^^^^^^^^^^^^
  File "/home/asan/miniconda3/envs/samplot-env/lib/python3.12/site-packages/samplot/samplot.py", line 2773, in get_read_data
    read_data["all_pairs"] = downsample_pairs(
                             ^^^^^^^^^^^^^^^^^
  File "/home/asan/miniconda3/envs/samplot-env/lib/python3.12/site-packages/samplot/samplot.py", line 2790, in downsample_pairs
    all_pairs[bam_i][hp_i] = sample_normal(
                             ^^^^^^^^^^^^^^
  File "/home/asan/miniconda3/envs/samplot-env/lib/python3.12/site-packages/samplot/samplot.py", line 539, in sample_normal
    for read_name in random.sample(inside_norm.keys(), max_depth):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asan/miniconda3/envs/samplot-env/lib/python3.12/random.py", line 413, in sample
    raise TypeError("Population must be a sequence.  "
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
```

**Comment by animesh** [comment]
Thanks @jbelyeu for suggestion, downgrading to python 3.10 and installing samplot

```
conda create -n samplot python=3.10
conda activate samplot
conda install -c bioconda samplot
```

seems to have worked 🙏
