### ISSUE TITLE
Can't load multiple CRAM?

### ISSUE THREAD

**Issue by davemcg** [ryanlayer/samplot#46]
This works
```
python3.5 ~/git/samplot/src/samplot.py -b sample_cram/OCA.24.cram -o oca_chr1.png -c 1 -s 72755343 -e 72764074 -t DEL
```

This doesn't
```
python3.5 ~/git/samplot/src/samplot.py -b sample_cram/OCA.24.cram,sample_cram/OCA.25.cram -o oca_chr1.png -c 1 -s 72755343 -e 72764074 -t DEL
```

```
[E::hts_open_format] Failed to open file sample_cram/OCA.24.cram,sample_cram/OCA.25.cram
Traceback (most recent call last):
  File "/home/mcgaugheyd/git/samplot/src/samplot.py", line 1212, in <module>
    bam_file = pysam.AlignmentFile(bam_file_name, "rb")
  File "pysam/libcalignmentfile.pyx", line 734, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 933, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] could not open alignment file `sample_cram/OCA.24.cram,sample_cram/OCA.25.cram`: No such file or directory```
```

I feel like I'm doing something stupid.....

**Comment by davemcg** [comment]
Wait a minute....

```
parser.add_argument("-b",
                  "--bams",
                  type=str,
                  nargs="+",
                  help="Space-delimited list of BAM/CRAM file names",
                  required=True)
```

**Comment by davemcg** [comment]
Yeah....that was it. Might want to update the README

**Comment by jbelyeu** [comment]
Apologies for that. Readme updated now
