### ISSUE TITLE
matplotlib version?

### ISSUE THREAD

**Issue by BioinformaticsBro** [ryanlayer/samplot#61]
Is there a specific version of matplotlib needed? I get this error when trying to run samplot.

```
samplot.py -n TEST -b BDE_209_C_capture.bam -o TEST.png -c chr1 -s 1000000 -e 1010000 -t INS
Warning: No data returned from fetch in region  chr1:1000000-1010000 from BDE_209_C_capture.bam
Traceback (most recent call last):
  File "/usr/local/genome/_plots/samplot/src/samplot.py", line 2140, in <module>
    max_coverage)   
  File "/usr/local/genome/_plots/samplot/src/samplot.py", line 1665, in plot_samples
    yaxis_label_fontsize)
  File "/usr/local/genome/_plots/samplot/src/samplot.py", line 1067, in plot_coverage
    alpha=.4)
  File "/home/fred/python2.7/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 4401, in fill_between
    collection = mcoll.PolyCollection(polys, **kwargs)
  File "/home/fred/python2.7/lib/python2.7/site-packages/matplotlib/collections.py", line 820, in __init__
    Collection.__init__(self, **kwargs)
  File "/home/fred/python2.7/lib/python2.7/site-packages/matplotlib/collections.py", line 135, in __init__
    self.update(kwargs)
  File "/home/fred/python2.7/lib/python2.7/site-packages/matplotlib/artist.py", line 757, in update
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property step
```

**Comment by ryanlayer** [comment]
The current README has a conda instruction that should help here.
